[selene]
base = "lua51"
name = "roblox"

# Environment Functions
[getgenv]
args = []

[getrenv]
args = []

[getreg]
args = []

[[getgc.args]]
type = "bool"
required = false
[getinstances]
args = []

[getnilinstances]
args = []

[getscripts]
args = []

[getloadedmodules]
args = []

[getconnections]
args = []

[[firesignal.args]]
type = "any"
required = true
[[firesignal.args]]
type = "number"
required = false

[[fireclickdetector.args]]
type = "any"
required = true
[[fireclickdetector.args]]
type = "number"
required = false
[[fireproximityprompt.args]]
type = "any"
required = true
[[fireproximityprompt.args]]
type = "number"
required = false

[[firetouchinterest.args]]
type = "any"
required = true
[[firetouchinterest.args]]
type = "number"
required = false

[[isnetworkowner.args]]
type = "any"
required = true

[[gethiddenproperty.args]]
type = "any"
required = true
[[gethiddenproperty.args]]
type = "string"
required = true

[[sethiddenproperty.args]]
type = "any"
required = true
[[sethiddenproperty.args]]
type = "string"
required = true
[[sethiddenproperty.args]]
type = "any"
required = true

[[setsimulationradius.args]]
type = "number"
required = true
[[setsimulationradius.args]]
type = "number"
required = false
# Script Functions
[[getsenv.args]]
type = "any"
required = true

[[getcallingscript.args]]
type = "any"
required = true

[[getscripthash.args]]
type = "any"
required = true
# Table Functions
[[getrawmetatable.args]]
type = "table"
required = true

[[setrawmetatable.args]]
type = "table"
required = true
[[setrawmetatable.args]]
type = "table"
required = true

[[setreadonly.args]]
type = "table"
required = true
[[setreadonly.args]]
type = "bool"
required = true

[[isreadonly.args]]
type = "table"
required = true

# Input Functions
[iswindowactive]
args = []

[[keypress.args]]
type = "number"
required = true

[[keyrelease.args]]
type = "number"
required = true

[mouse1click]
args = []

[mouse1press]
args = []

[mouse1release]
args = []

[mouse2click]
args = []

[mouse2press]
args = []

[mouse2release]
args = []

[[mousescroll.args]]
type = "number"
required = true

[[mousemoverel.args]]
type = "number"
required = true
[[mousemoverel.args]]
type = "number"
required = true

[[mousemoveabs.args]]
type = "number"
required = true
[[mousemoveabs.args]]
type = "number"
required = true

# Hooking Functions
[[hookfunction.args]]
type = "function"
required = true
[[hookfunction.args]]
type = "function"
required = true

[[hookmetamethod.args]]
type = "any"
required = true
[[hookmetamethod.args]]
type = "string"
required = true
[[hookmetamethod.args]]
type = "function"
required = true

[[newcclosure.args]]
type = "function"
required = true
# Reflection Functions
[[loadstring.args]]
type = "string"
required = true
[[loadstring.args]]
type = "string"
required = false

[checkcaller]
args = []

[[dumpstring.args]]
type = "string"
required = true

[[decompile.args]]
type = "any"
required = true
[[decompile.args]]
type = "number"
required = false

# Console Functions
[[rconsoleprint.args]]
type = "string"
required = true

[[rconsoleinfo.args]]
type = "string"
required = true

[[rconsolewarn.args]]
type = "string"
required = true

[[rconsoleerr.args]]
type = "string"
required = true

[rconsoleclear]
args = []

[[rconsolename.args]]
type = "string"
required = true

[rconsoleinput]
args = []

[[printconsole.args]]
type = "string"
required = true
[[printconsole.args]]
type = "any"
required = true
[[printconsole.args]]
type = "any"
required = true
[[printconsole.args]]
type = "any"
required = true

# Filesystem Functions
[[readfile.args]]
type = "string"
required = true

[[writefile.args]]
type = "string"
required = true
[[writefile.args]]
type = "string"
required = true

[[appendfile.args]]
type = "string"
required = true
[[appendfile.args]]
type = "string"
required = true

[[loadfile.args]]
type = "string"
required = true

[[listfiles.args]]
type = "string"
required = true

[[isfile.args]]
type = "string"
required = true

[[isfolder.args]]
type = "string"
required = true

[[makefolder.args]]
type = "string"
required = true

[[delfolder.args]]
type = "string"
required = true

[[delfile.args]]
type = "string"
required = true

# Miscellaneous Functions
[[setclipboard.args]]
type = "string"
required = true

[[setfflag.args]]
type = "string"
required = true

[getnamecallmethod]
args = []

[[setnamecallmethod.args]]
type = "string"
required = true

[[getsynasset.args]]
type = "string"
required = true

[[getspecialinfo.args]]
type = "any"
required = true

[[saveinstance.args]]
type = "table"
required = true

[[messagebox.args]]
type = "string"
required = true
[[messagebox.args]]
type = "string"
required = true
[[messagebox.args]]
type = "number"
required = true

# Libraries

	# Bit Library
	[[bit.bdiv.args]]
	type = "number"
	required = true
	[[bit.bdiv.args]]
	type = "number"
	required = true

	[[bit.badd.args]]
	type = "number"
	required = true
	[[bit.badd.args]]
	type = "number"
	required = true

	[[bit.bsub.args]]
	type = "number"
	required = true
	[[bit.bsub.args]]
	type = "number"
	required = true

	[[bit.bdiv.args]]
	type = "number"
	required = true
	[[bit.bdiv.args]]
	type = "number"
	required = true

	[[bit.bmul.args]]
	type = "number"
	required = true
	[[bit.bmul.args]]
	type = "number"
	required = true

	[[bit.band.args]]
	type = "number"
	required = true
	[[bit.band.args]]
	type = "number"
	required = true

	[[bit.bor.args]]
	type = "number"
	required = true
	[[bit.bor.args]]
	type = "number"
	required = true

	[[bit.bxor.args]]
	type = "number"
	required = true
	[[bit.bxor.args]]
	type = "number"
	required = true

	[[bit.bnot.args]]
	type = "number"
	required = true

	[[bit.bswap.args]]
	type = "number"
	required = true

	[[bit.rol.args]]
	type = "number"
	required = true
	[[bit.rol.args]]
	type = "number"
	required = true

	[[bit.tohex.args]]
	type = "number"
	required = true

	[[bit.tobit.args]]
	type = "number"
	required = true

	[[bit.lshift.args]]
	type = "number"
	required = true
	[[bit.lshift.args]]
	type = "number"
	required = true

	[[bit.rshift.args]]
	type = "number"
	required = true
	[[bit.rshift.args]]
	type = "number"
	required = true

	[[bit.arshift.args]]
	type = "number"
	required = true
	[[bit.arshift.args]]
	type = "number"
	required = true

	# Crypt Library
	[[syn.crypt.encrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.encrypt.args]]
	type = "string"
	required = true

	[[syn.crypt.decrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.decrypt.args]]
	type = "string"
	required = true

	[[syn.crypt.base64.encode.args]]
	type = "string"
	required = true

	[[syn.crypt.base64.encode.args]]
	type = "string"
	required = true

	[[syn.crypt.base64.decode.args]]
	type = "string"
	required = true

	[[syn.crypt.hash.args]]
	type = "string"
	required = true

	[[syn.crypt.derive.args]]
	type = "string"
	required = true
	[[syn.crypt.derive.args]]
	type = "number"
	required = true

	[[syn.crypt.random.args]]
	type = "number"
	required = true

	[[syn.crypt.custom.encrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.encrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.encrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.encrypt.args]]
	type = "string"
	required = true

	[[syn.crypt.custom.decrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.decrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.decrypt.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.decrypt.args]]
	type = "string"
	required = true

	[[syn.crypt.custom.hash.args]]
	type = "string"
	required = true
	[[syn.crypt.custom.hash.args]]
	type = "string"
	required = true

	# Debug Library

	# Drawing Library
	[[Drawing.new.args]]
	type = "string"
	required = true

	[Drawing.Fonts.UI]
	property = true

	[Drawing.Fonts.System]
	property = true

	[Drawing.Fonts.Plex]
	property = true

	[Drawing.Fonts.Monospace]
	property = true

	# Syn Library

	# Websocket Library